### ISSUE TITLE
Dynamic Configuration Missing

### ISSUE THREAD

**Issue by sivizius** [pendulum-project/ntpd-rs#1343]
According to https://docs.ntpd-rs.pendulum-project.org/development/code-structure/#configuration-task, it is possible to configure ntpd-rs dynamically via a unix-socket. However, this was removed with https://github.com/pendulum-project/ntpd-rs/commit/01df0145d114514b98b6d8eb081f3cd94cbc129f, right? Is there a reason for such a breaking change, which was not in a major release and even back-ported to older releases? I cannot find any documentation about why this was necessary, only this section in the docs that state, this is still possible.

Is there any other way to add/remove/… sources/servers/… at runtime?

**Comment by rnijveld** [comment]
There currently isn't a way to configure anything at runtime. Pre-1.0 we used to have a mechanism in place, but the configuration options were very limited, only allowing the dynamic configuration of the log level. However we didn't like the interface and there were some concerns surrounding safety. Because we wanted to get to a stable interface for post 1.0 we decided to remove the functionality for the time being. This was during development of 1.0.0, so was first released in a major version, it was never backported to older releases. The change was in the 1.0.0 changelog.

Currently we don't really have much of a plan to bring the dynamic configuration interface back. Aside from bringing the old interface back, we have been thinking about some alternatives, e.g. allowing a SIGHUB to do runtime reloading of the config or making restarting cheaper by remembering some parts of the internal state. But nothing concrete has been decided yet.

The docs still being there is an oversight though, they should be updated.
