### ISSUE TITLE
Update documentation for `ntp-ctl`

### ISSUE THREAD

**Issue by moderation** [pendulum-project/ntpd-rs#913]
The documentation for `test-binaries` at https://github.com/pendulum-project/ntpd-rs/blob/main/README.md?plain=1#L70 doesn't include `peer-state` which appears to replace `ntp-ctl peers`.

`ntp-ctl` documentation at https://github.com/pendulum-project/ntpd-rs/blob/main/MANAGEMENT_CLIENT.md out of date with most options changed.

```
ntp-ctl - ntp-daemon monitoring

usage: ntp-ctl validate [-c PATH]
       ntp-ctl status [-f FORMAT] [-c PATH] [-o PATH]
       ntp-ctl -h | ntp-ctl -v

Options:
  -f, --format=FORMAT                  which format to use for printing statistics [plain, prometheus]
  -c, --config=CONFIG                  which configuration file to read the socket paths from
  -o, --observation-socket=SOCKET      path of the observation socket
```

I can't get any of these commands to work including the command run at https://github.com/pendulum-project/ntpd-rs/blob/main/.github/workflows/build.yaml#L168

`ntp-metrics-exporter` appears to replace `ntp-ctl prometheus`.

**Comment by moderation** [comment]
`peer-state` removed from `test-binaries` with https://github.com/pendulum-project/ntpd-rs/pull/942

`ntp-ctl` still doesn't work and documentation out of date. Doesn't appear to be a way to display current peers or status.

**Comment by davidv1992** [comment]
Apologies that this took a bit for us to get to. We were doing some significant internal cleanup for the past month in preparation for a version 1.0 release, and in that process we managed to entirely brick the ntp-ctl binary due to incorrect parameter parsing. There is a pull request open to fix that now. As for the documentation, we are in the process of updating it all, but writing good documentation takes some time, we hope to have finished that somewhere in the next month or so. Issues for the documentation are already open separately, so I will close this once the ntp-ctl fixing binary is merged.
